# Generated by Django 4.0.3 on 2022-04-27 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='edited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipesedited', to=settings.AUTH_USER_MODEL),
        ),
    ]
