# Generated by Django 4.0.3 on 2022-04-27 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_recipe_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='edited',
        ),
        migrations.AddField(
            model_name='recipe',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipeseditedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
